const axios = require('axios')
// const apiKey = '?apiKey=556d5c003785468ab5aa696a128a3d3a'
const apiKey = 'apiKey=5bb1646af40448c4bd763b79205bc198'
const urlBase = 'https://api.spoonacular.com'

const user = {
  "username":"api-52495-piotrostr",
  "hash":"c7d551c6e13e41681b05852ffcfa6ebbb20fbf09"
}

export const johny = {
  username: 'yoniaibi',
  hash: 'e4a10a305427619e90290391d8fc38370ffca93d'
}

const getLastMonday = () => {
  let date = new Date()
  let day = date.getDay()
  let lastMonday = new Date()
  if (date.getDay() === 0) {
    lastMonday.setDate(date.getDate() - 7)
  } else {
    lastMonday.setDate(date.getDate() - (day-1))
  }
  return lastMonday
}

const getUserPlan = () => {
  /** @returns user plan for the most recent week assuming that its always starting on monday **/
  let date = getLastMonday()
  date = date.toISOString().split('T')[0]
  const url = `${urlBase}/mealplanner/${user.username}/week/${date}?hash=${user.hash}${apiKey}`
  axios.get(url)
    .then((res) => {console.log(res.data); return res.data})
    .catch((err) => console.log(err))
    .then(() => console.log(url))
}

const addMealToUserPlan = (user, date, slot, position) => {
  const url = `${urlBase}/mealplanner/${user.username}/items?hash=${user.hash}&${apiKey}`
  axios.post(url, { "date": date, "slot": slot, "position": position,
    "type": "INGREDIENTS", "value": { "ingredients": [{"name": "1 banana"}]}})
    .then((res) => {console.log(res.data); return res.data})
    .catch((err) => console.log(err))
    .then(() => console.log(url))
}

// console.log(addMealToUserPlan(user, date, 1, 3))
// console.log(getUserPlan())

export const getUserMealPlanTemplates = (username, hash) => {
  const url = `https://api.spoonacular.com/mealplanner/${username}/templates?hash=${hash}&${apiKey}`
  axios.get(url)
    .then((res) => {console.log(res.data); return res.data})
    .catch((err) => console.log(err))
    .then(() => console.log(url))
}

const getPublicTemplates = () => {
  const url = `https://api.spoonacular.com/mealplanner/public-templates?${apiKey}`
  axios.get(url)
    .then((res) => {console.log(res.data); return res.data})
    .catch((err) => console.log(err))
    .then(() => console.log(url))
}

export const fetchDataJohny = async () => {
  const base = 'https://api.spoonacular.com/mealplanner';
  // const apiKey = '?apiKey=556d5c003785468ab5aa696a128a3d3a';
  const apiKey = '?apiKey=5bb1646af40448c4bd763b79205bc198'
  const dayToday = new Date().getDay() -1 // sunday is 0
  let id = 2807  // can be 2807, 2813, 2815, 2817, 2819, 2821
  const url = base + `/${johny.username}/templates/${id}` + apiKey + `&hash=${johny.hash}`
  const res = await axios.get(url).catch((err) => console.log(err))
  console.log(res.data)
  let meals = Object.values(res.data.days)
  meals = [...meals.slice(dayToday), ...meals.slice(0, dayToday)]
  return meals
}


if (require.main === module) {
  getUserMealPlanTemplates(johny.username, johny.hash)
  fetchDataJohny().then(r => console.log(r))
  // getPublicTemplates()
  // getUserMealPlanTemplates(user.username, user.hash)
}


/** @returns shopping list for the next week generated by spoonacular api **/
export const generateShoppingList = (username, hash) => {
  let currentTime = new Date()
  let currentMonth
  currentTime.getMonth() + 1 < 9 ?
    currentMonth = `0${currentTime.getMonth() + 1}`
    : currentMonth = currentTime.getMonth() + 1
  let currentDate = `${currentTime.getFullYear()}-${currentMonth}-${currentTime.getDate()}`
  let dateInAWeek = `${currentTime.getFullYear()}-${currentMonth}-${currentTime.getDate() + 7}`
  const apiKey = 'apiKey=5bb1646af40448c4bd763b79205bc198'
  const base = 'https://api.spoonacular.com/mealplanner/'
  const url = base + username + `/shopping-list/${currentDate}/${dateInAWeek}?hash=${hash}&${apiKey}`
  axios.post(url).then(r => {console.log(r.data); r.data}).catch(e => console.log(e))
}
