# Generated by Django 3.1 on 2020-08-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('store', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energy', models.CharField(max_length=20)),
                ('fat', models.CharField(max_length=20)),
                ('saturates', models.CharField(max_length=20)),
                ('carbohydrate', models.CharField(max_length=20)),
                ('sugars', models.CharField(max_length=20)),
                ('fibre', models.CharField(max_length=20)),
                ('protein', models.CharField(max_length=20)),
                ('salt', models.CharField(max_length=20)),
            ],
        ),
    ]
