# Generated by Django 3.1.1 on 2021-01-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_foodcupboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store', models.CharField(max_length=20)),
                ('amount', models.FloatField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodCupboard',
        ),
        migrations.DeleteModel(
            name='FruitVeg',
        ),
        migrations.DeleteModel(
            name='MeatFish',
        ),
    ]
