# Generated by Django 3.1.1 on 2021-01-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210122_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
